---
version: '3'

services:
  zip2john:
    build:
      context: ./build/john
      dockerfile: Dockerfile
    image: dceoy/john:latest
    volumes:
      - ${PWD}:/host:ro
    working_dir: /host
    entrypoint:
      - /opt/john/run/zip2john
  hashcat:
    build:
      context: ./build/hashcat
      dockerfile: Dockerfile
    image: dceoy/hashcat:latest
    volumes:
      - ${PWD}:/host:ro
    working_dir: /host
    entrypoint:
      - /usr/local/bin/hashcat
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
                - utility
