---
version: '3'

services:
  john:
    build:
      context: ./build/john
      dockerfile: Dockerfile
    image: dceoy/john:latest
  hashcat:
    build:
      context: ./build/hashcat
      dockerfile: Dockerfile
    image: dceoy/hashcat:latest
